### ISSUE TITLE
发送完之后 我清空 textView = @""字符 高度没有复原 

### ISSUE THREAD

**Issue by uncleRX** [LMMIsGood/LiuqsEmoticonkeyboard#3]
![71b30954-72c6-488f-aa9e-b4002e8f6edd](https://user-images.githubusercontent.com/16251490/31043865-2588acf6-a589-11e7-9780-41c62c574ba9.png)
 还有当表情跟英文字母一起存在的时候 转码格式有问题,   单表情的时候是正常的 比如 [得意][开心]
加文字之后 [/u123/u3222]wssjasjas  ,别人只能接受到  英文字母 
希望结果应该是  "[得意][开心]wssjasjas"

**Comment by Liuqs-MrPotato** [comment]
需要更新一下的，你手动清空没有更新textView，所以不会改变，尝试看一下发送事件在内部做了啥子!
